apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-server
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: True